In [2]:
import numpy as np
import pandas as pd

In [3]:
rating = pd.read_csv('../Datasets/FIFA/FIFA23_rating/player_rating.csv')

In [4]:
rating.head()

,contractvaliduntil_diff,gkdiving_diff,birthdate,playerjerseyname,def,longshots,preferredposition4label,volleys,ranking_diff,contractvaliduntil,...,gkkicking_diff,gkreflexes_diff,potential_diff,lastnameid_diff,interceptions,shortpassing,preferredposition1_diff,preferredposition4_diff,teamname,primaryKey
0,0,0,2/4/1994 0:00,Alexia,72,90,NaN,90,0,2024,...,0,0,0,0,79,95,0,0,Spain Women,227203
1,0,0,9/10/1993 0:00,Kerr,42,89,NaN,92,0,2024,...,0,0,0,0,24,78,0,0,Chelsea,227125
2,0,0,7/20/1990 0:00,Renard,93,65,NaN,55,0,2026,...,0,0,0,0,90,84,0,0,Olympique Lyonnais,227316
3,0,0,7/10/1995 0:00,Hegerberg,39,89,NaN,90,0,2024,...,0,0,0,0,23,84,0,0,Olympique Lyonnais,227310
4,0,0,11/1/1998 0:00,Katoto,39,87,NaN,91,0,2025,...,0,0,0,0,27,87,0,0,Paris Saint-Germain,246272

In [5]:
na_s = rating.isnull().sum()

In [6]:
col_0 = (rating == 0).sum(axis = 0)

In [7]:
drop_list = [i for i in na_s.index if na_s[i] > 400]

In [8]:
drop_list

['preferredposition4label', 'commonname', 'preferredposition3label']

In [9]:
for i in col_0.index:
    if col_0[i]>400:
        drop_list.append(i)

In [10]:
drop_list

['preferredposition4label',
 'commonname',
 'preferredposition3label',
 'contractvaliduntil_diff',
 'gkdiving_diff',
 'ranking_diff',
 'defensiveworkrate_diff',
 'standingtackle_diff',
 'acceleration_diff',
 'strength_diff',
 'freekickaccuracy_diff',
 'dribbling_diff',
 'ballcontrol_diff',
 'sprintspeed_diff',
 'nationality_diff',
 'positioning_diff',
 'attackingworkrate_diff',
 'aggression_diff',
 'teamid_diff',
 'gkpositioning_diff',
 'stamina_diff',
 'preferredposition3_diff',
 'agility_diff',
 'preferredposition2_diff',
 'longshots_diff',
 'vision_diff',
 'height_diff',
 'gkhandling_diff',
 'interceptions_diff',
 'weakfootabilitytypecode_diff',
 'reactions_diff',
 'commonnameid',
 'curve_diff',
 'defensiveawareness_diff',
 'commonnameid_diff',
 'longpassing_diff',
 'primaryKey_diff',
 'slidingtackle_diff',
 'composure_diff',
 'crossing_diff',
 'shortpassing_diff',
 'balance_diff',
 'finishing_diff',
 'leagueid_diff',
 'preferredfoot_diff',
 'weight_diff',
 'overall_diff',
 'playerjerseynameid_diff',
 'shotpower_diff',
 'firstnameid_diff',
 'volleys_diff',
 'headingaccuracy_diff',
 'jumping_diff',
 'penalties_diff',
 'skillmoves_diff',
 'isfakeplayer',
 'gender_diff',
 'gkkicking_diff',
 'gkreflexes_diff',
 'potential_diff',
 'lastnameid_diff',
 'preferredposition1_diff',
 'preferredposition4_diff']

In [11]:
rating.drop(columns = drop_list, inplace = True)

In [12]:
rating

,birthdate,playerjerseyname,def,longshots,volleys,contractvaliduntil,balance,shotpower,defensiveawareness,height,...,iteration,preferredposition2,preferredposition2label,preferredposition4,gkdiving,firstnameid,interceptions,shortpassing,teamname,primaryKey
0,2/4/1994 0:00,Alexia,72,90,90,2024,78,81,60,173,...,fifa-23-womens-sep30-2,27,LW,-1,15,1403,79,95,Spain Women,227203
1,9/10/1993 0:00,Kerr,42,89,92,2024,82,91,44,168,...,fifa-23-womens-sep30-2,-1,NaN,-1,7,29874,24,78,Chelsea,227125
2,7/20/1990 0:00,Renard,93,65,55,2026,34,85,93,187,...,fifa-23-womens-sep30-2,-1,NaN,-1,7,35451,90,84,Olympique Lyonnais,227316
3,7/10/1995 0:00,Hegerberg,39,89,90,2024,47,86,42,176,...,fifa-23-womens-sep30-2,-1,NaN,-1,15,436,23,84,Olympique Lyonnais,227310
4,11/1/1998 0:00,Katoto,39,87,91,2025,68,86,37,177,...,fifa-23-womens-sep30-2,-1,NaN,-1,14,21853,27,87,Paris Saint-Germain,246272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,11/11/1995 0:00,Graham,51,73,55,2023,64,74,45,160,...,fifa-23-womens-sep30-2,21,SS,-1,14,18235,45,79,Tottenham Hotspur,265261
496,11/8/1995 0:00,Grimshaw,34,66,67,2027,79,66,25,173,...,fifa-23-womens-sep30-2,-1,NaN,-1,8,6708,31,74,Scotland Women,266603
497,1/28/1999 0:00,K.Holmgaard,74,53,43,2024,41,56,73,180,...,fifa-23-womens-sep30-2,-1,NaN,-1,14,17541,71,74,Everton,265012
498,7/26/1998 0:00,Diana G.,74,23,29,2026,69,45,75,167,...,fifa-23-womens-sep30-2,-1,NaN,-1,9,8605,73,72,Portugal Women,261853
499,1/3/1995 0:00,Tarrieu,40,59,59,2023,83,65,41,160,...,fifa-23-womens-sep30-2,12,RM,-1,8,24153,40,73,Rodez Aveyron Football,265882

In [13]:
list(rating.isnull().sum())

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 225,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [14]:
rating.columns

Index(['birthdate', 'playerjerseyname', 'def', 'longshots', 'volleys',
       'contractvaliduntil', 'balance', 'shotpower', 'defensiveawareness',
       'height', 'longpassing', 'standingtackle', 'crossing', 'nationality',
       'status', 'gender', 'curve', 'slidingtackle', 'gkreflexes', 'finishing',
       'surname', 'lastnameid', 'leaguename', 'aggression', 'gkpositioning',
       'sprintspeed', 'headingaccuracy', 'fullNameForSearch', 'reactions',
       'ranking', 'overall_rating', 'phy', 'penalties', 'strength',
       'skillmoves', 'stamina', 'weakfootabilitytypecode', 'ballcontrol',
       'gkhandling', 'acceleration', 'pac', 'teamid', 'hasphoto', 'dri',
       'potential', 'pas', 'weight', 'preferredfoot', 'freekickaccuracy',
       'vision', 'leagueid', 'sho', 'agility', 'firstname',
       'playerjerseynameid', 'composure', 'jumping', 'gkkicking',
       'preferredposition1label', 'defensiveworkrate', 'dribbling',
       'preferredposition1', 'positioning', 'attackingworkrate',
       'preferredposition3', 'iteration', 'preferredposition2',
       'preferredposition2label', 'preferredposition4', 'gkdiving',
       'firstnameid', 'interceptions', 'shortpassing', 'teamname',
       'primaryKey'],
      dtype='object')

In [15]:
rating.to_csv('rating_new.csv', index = False)