In [52]:
import numpy as np
import pandas as pd
from datetime import datetime
import requests
from bs4 import BeautifulSoup

In [53]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [54]:
rating23_2 = pd.read_csv('../Datasets/FIFA/FIFA23_rating/rating_23.csv')
rating23 = pd.read_csv('../Datasets/FIFA/FIFA23_rating/rating_23_Feb.csv')
rating22 = pd.read_csv('../Datasets/FIFA/FIFA22_rating/female_players_22.csv')
rating21 = pd.read_csv('../Datasets/FIFA/FIFA22_rating/female_players_21.csv')
rating20 = pd.read_csv('../Datasets/FIFA/FIFA22_rating/female_players_20.csv')
rating19 = pd.read_csv('../Datasets/FIFA/FIFA22_rating/female_players_19.csv')
rating18 = pd.read_csv('../Datasets/FIFA/FIFA22_rating/female_players_18.csv')
rating17 = pd.read_csv('../Datasets/FIFA/FIFA22_rating/female_players_17.csv')
rating16 = pd.read_csv('../Datasets/FIFA/FIFA22_rating/female_players_16.csv')

In [55]:
def drop_1(dataset):
    '''drop columns with more than 200 missing data or more than 200 values = 0'''
    na_s = rating23.isnull().sum()
    col_0 = (rating23 == 0).sum(axis = 0)
    drop_list = [i for i in na_s.index if na_s[i] > 200]
    for i in col_0.index:
        if col_0[i]>200:
            drop_list.append(i)
    dataset.drop(columns = drop_list, inplace = True)

In [56]:
drop_1(rating23_2)
drop_1(rating23)
drop_1(rating22)
drop_1(rating21)
drop_1(rating20)
drop_1(rating19)
drop_1(rating18)
drop_1(rating17)
drop_1(rating16)

In [57]:
new_col_1 = ['fullNameForSearch', 'nationality', 'birthdate', 'preferredposition1label', 'height', 'weight', 'overall_rating','pac','sho','pas','dri','def','phy', 
           'longshots', 'volleys','balance', 'shotpower', 
            'longpassing', 'standingtackle', 'crossing',
           'curve', 'finishing','slidingtackle','aggression','sprintspeed', 'headingaccuracy', 
           'reactions', 'ranking', 'penalties', 'strength', 'skillmoves', 'stamina', 
           'ballcontrol', 'acceleration',  'preferredfoot',
           'vision',  'agility', 'composure', 'jumping', 
           'interceptions', 'shortpassing']

In [58]:
rating23_new = rating23[new_col_1]

In [59]:
rating23_new['birthdate']=rating23_new.apply(lambda x:x['birthdate'].split()[0], axis=1)

rating23_new['birthdate'] = rating23_new.apply(lambda x:datetime.strptime(x['birthdate'], '%m/%d/%Y').year, axis =1)

rating23_new = rating23_new.rename({'fullNameForSearch':'full_name', 'birthdate':'birthyear', 'preferredposition1label': 'position'}, axis=1)

C:\Users\lorih\AppData\Local\Temp\ipykernel_166676\228554067.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rating23_new['birthdate']=rating23_new.apply(lambda x:x['birthdate'].split()[0], axis=1)
C:\Users\lorih\AppData\Local\Temp\ipykernel_166676\228554067.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rating23_new['birthdate'] = rating23_new.apply(lambda x:datetime.strptime(x['birthdate'], '%m/%d/%Y').year, axis =1)

In [60]:
rating23_new.head()

,full_name,nationality,birthyear,position,height,weight,overall_rating,pac,sho,pas,dri,def,phy,longshots,volleys,balance,shotpower,longpassing,standingtackle,crossing,curve,finishing,slidingtackle,aggression,sprintspeed,headingaccuracy,reactions,ranking,penalties,strength,skillmoves,stamina,ballcontrol,acceleration,preferredfoot,vision,agility,composure,jumping,interceptions,shortpassing
0,Alexia Putellas Segura,45,1994,CM,173,67,92,80,90,92,91,72,75,90,90,78,81,91,82,87,89,94,64,58,78,74,95,1,91,75,5,90,94,82,2,95,76,91,75,79,95
1,Sam Kerr,195,1993,ST,168,66,91,87,91,75,90,42,83,89,92,82,91,55,39,80,76,93,35,70,85,91,93,2,79,86,4,87,92,89,1,83,90,92,91,24,78
2,Wendie Renard,18,1990,CB,187,70,91,67,72,71,72,93,87,65,55,34,85,87,94,51,65,70,91,88,66,96,90,3,75,93,2,75,85,68,1,59,53,84,86,90,84
3,Ada Hegerberg,36,1995,ST,176,68,91,85,91,77,87,39,77,89,90,47,86,72,33,71,79,94,29,65,86,93,93,4,86,81,4,75,91,83,1,76,74,86,89,23,84
4,Marie Katoto,18,1998,ST,177,66,90,88,90,78,86,39,74,87,91,68,86,70,35,71,71,93,29,44,88,92,90,5,82,81,4,82,89,89,1,79,80,85,86,27,87

In [61]:
rating23_new.rename(columns = {'overall_rating':'overall','pac':'pace', 'sho':'shooting', 'pas': 'passing', 
                               'dri':'dribbling','def':'defending'}, inplace = True)

In [62]:
rating23_2_new = rating23_2[new_col_1]
rating23_2_new['birthdate']=rating23_2_new.apply(lambda x:x['birthdate'].split()[0], axis=1)

rating23_2_new['birthdate'] = rating23_2_new.apply(lambda x:datetime.strptime(x['birthdate'], '%m/%d/%Y').year, axis =1)

rating23_2_new = rating23_2_new.rename({'fullNameForSearch':'full_name', 'birthdate':'birthyear', 'preferredposition1label': 'position'}, axis=1)
rating23_2_new.rename(columns = {'overall_rating':'overall','pac':'pace', 'sho':'shooting', 'pas': 'passing', 
                               'dri':'dribbling','def':'defending'}, inplace = True)

C:\Users\lorih\AppData\Local\Temp\ipykernel_166676\3048508127.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rating23_2_new['birthdate']=rating23_2_new.apply(lambda x:x['birthdate'].split()[0], axis=1)
C:\Users\lorih\AppData\Local\Temp\ipykernel_166676\3048508127.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rating23_2_new['birthdate'] = rating23_2_new.apply(lambda x:datetime.strptime(x['birthdate'], '%m/%d/%Y').year, axis =1)

In [63]:
rating23_new.columns == rating23_2_new.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [64]:
def get_nation(df):
    nation_list = df.nationality.unique()
    nation_dict = {}
    for num in nation_list:
        r = requests.get('https://www.ea.com/games/fifa/fifa-23/womens-ratings/player-filter/player-nationality/'+str(num))
        soup = BeautifulSoup(r.content, 'html.parser')
        title = soup.find('title')
        nation_dict[num] = title.text.split()[0]
    df['nationality'] = df['nationality'].replace(nation_dict)
    return df

In [67]:
rating23_new = get_nation(rating23_new)

In [65]:
rating23_2_new = get_nation(rating23_2_new)

### Check what players were added or removed

In [69]:
merged = pd.merge(rating23_new, rating23_2_new, on=['full_name','nationality'], how='outer', indicator=True)

In [70]:
merged.head()

,full_name,nationality,birthyear_x,position_x,height_x,weight_x,overall_x,pace_x,shooting_x,passing_x,dribbling_x,defending_x,phy_x,longshots_x,volleys_x,balance_x,shotpower_x,longpassing_x,standingtackle_x,crossing_x,curve_x,finishing_x,slidingtackle_x,aggression_x,sprintspeed_x,headingaccuracy_x,reactions_x,ranking_x,penalties_x,strength_x,skillmoves_x,stamina_x,ballcontrol_x,acceleration_x,preferredfoot_x,vision_x,agility_x,composure_x,jumping_x,interceptions_x,shortpassing_x,birthyear_y,position_y,height_y,weight_y,overall_y,pace_y,shooting_y,passing_y,dribbling_y,defending_y,phy_y,longshots_y,volleys_y,balance_y,shotpower_y,longpassing_y,standingtackle_y,crossing_y,curve_y,finishing_y,slidingtackle_y,aggression_y,sprintspeed_y,headingaccuracy_y,reactions_y,ranking_y,penalties_y,strength_y,skillmoves_y,stamina_y,ballcontrol_y,acceleration_y,preferredfoot_y,vision_y,agility_y,composure_y,jumping_y,interceptions_y,shortpassing_y,_merge
0,Alexia Putellas Segura,Spain,1994.0,CM,173.0,67.0,92.0,80.0,90.0,92.0,91.0,72.0,75.0,90.0,90.0,78.0,81.0,91.0,82.0,87.0,89.0,94.0,64.0,58.0,78.0,74.0,95.0,1.0,91.0,75.0,5.0,90.0,94.0,82.0,2.0,95.0,76.0,91.0,75.0,79.0,95.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,Sam Kerr,Australia,1993.0,ST,168.0,66.0,91.0,87.0,91.0,75.0,90.0,42.0,83.0,89.0,92.0,82.0,91.0,55.0,39.0,80.0,76.0,93.0,35.0,70.0,85.0,91.0,93.0,2.0,79.0,86.0,4.0,87.0,92.0,89.0,1.0,83.0,90.0,92.0,91.0,24.0,78.0,1993.0,ST,168.0,66.0,91.0,87.0,91.0,74.0,90.0,42.0,83.0,89.0,92.0,82.0,91.0,64.0,39.0,70.0,76.0,93.0,30.0,70.0,85.0,91.0,91.0,1.0,75.0,86.0,4.0,87.0,92.0,89.0,1.0,79.0,90.0,92.0,91.0,24.0,78.0,both
2,Wendie Renard,France,1990.0,CB,187.0,70.0,91.0,67.0,72.0,71.0,72.0,93.0,87.0,65.0,55.0,34.0,85.0,87.0,94.0,51.0,65.0,70.0,91.0,88.0,66.0,96.0,90.0,3.0,75.0,93.0,2.0,75.0,85.0,68.0,1.0,59.0,53.0,84.0,86.0,90.0,84.0,1990.0,CB,187.0,70.0,90.0,62.0,72.0,71.0,71.0,93.0,87.0,65.0,55.0,34.0,85.0,87.0,94.0,51.0,65.0,70.0,90.0,88.0,60.0,96.0,90.0,3.0,75.0,93.0,2.0,75.0,81.0,65.0,1.0,59.0,53.0,84.0,86.0,90.0,84.0,both
3,Ada Hegerberg,Norway,1995.0,ST,176.0,68.0,91.0,85.0,91.0,77.0,87.0,39.0,77.0,89.0,90.0,47.0,86.0,72.0,33.0,71.0,79.0,94.0,29.0,65.0,86.0,93.0,93.0,4.0,86.0,81.0,4.0,75.0,91.0,83.0,1.0,76.0,74.0,86.0,89.0,23.0,84.0,1995.0,ST,176.0,68.0,90.0,83.0,91.0,77.0,87.0,39.0,77.0,89.0,90.0,47.0,86.0,72.0,33.0,71.0,79.0,94.0,30.0,65.0,85.0,93.0,92.0,4.0,86.0,81.0,4.0,75.0,91.0,81.0,1.0,76.0,74.0,86.0,89.0,23.0,84.0,both
4,Marie Katoto,France,1998.0,ST,177.0,66.0,90.0,88.0,90.0,78.0,86.0,39.0,74.0,87.0,91.0,68.0,86.0,70.0,35.0,71.0,71.0,93.0,29.0,44.0,88.0,92.0,90.0,5.0,82.0,81.0,4.0,82.0,89.0,89.0,1.0,79.0,80.0,85.0,86.0,27.0,87.0,1998.0,ST,177.0,66.0,89.0,87.0,90.0,78.0,85.0,39.0,73.0,87.0,91.0,68.0,86.0,70.0,35.0,71.0,71.0,93.0,29.0,44.0,87.0,92.0,88.0,7.0,82.0,81.0,4.0,78.0,88.0,88.0,1.0,79.0,80.0,85.0,86.0,27.0,86.0,both

In [71]:
diff = merged.loc[merged['_merge'] != 'both']

In [72]:
diff = diff[['full_name','nationality', '_merge']]

In [74]:
FIFA_update = diff.replace({'left_only':'removed', 'right_only':'added'})

In [75]:
FIFA_update = FIFA_update.rename(columns = {'_merge': 'action'})

In [76]:
FIFA_update = FIFA_update.sort_values('nationality')

In [77]:
FIFA_update.action.value_counts()

added      201
removed    136
both         0
Name: action, dtype: int64

In [79]:
FIFA_update.head()

            full_name nationality   action
376    Soledad Jaimes   Argentina  removed
295    Eliana Stabile   Argentina  removed
408     Adriana Sachs   Argentina  removed
397  Agustina Barroso   Argentina  removed
373     Emily Gielnik   Australia  removed

### Combine two dataset. If a player's rating changed, use the newer one.

In [108]:
rating23_new.set_index('full_name', inplace=True)
rating23_2_new.set_index('full_name', inplace=True)

In [109]:
mask = ~rating23_new.index.isin(rating23_2_new.index)

In [110]:
rating23_new_masked = rating23_new[mask]

In [114]:
rating23_combined = pd.concat([rating23_new_masked, rating23_2_new])

In [116]:
rating23_combined.shape

(700, 40)

In [117]:
rating23_combined.nationality.value_counts()

United         125
France         108
England         73
Germany         42
Spain           41
Sweden          28
Canada          24
Holland         20
Scotland        19
Belgium         16
Norway          16
Iceland         15
Portugal        13
Mexico          13
Australia       12
Denmark         12
Argentina       11
China           10
Wales            9
Italy            9
Japan            8
Switzerland      8
Poland           7
Republic         7
Brazil           5
Austria          5
Haiti            5
Finland          5
Jamaica          4
New              4
Czech            3
Cameroon         3
Nigeria          3
Korea            2
Slovakia         2
Costa            2
Slovenia         2
Venezuela        1
Bosnia           1
Serbia           1
Côte             1
Chile            1
Morocco          1
Greece           1
Mali             1
Russia           1
Name: nationality, dtype: int64

In [119]:
rating23_combined.reset_index(inplace = True)

In [121]:
rating23_combined.to_csv('../Datasets/cleaned_data/FIFA23_rating_combined.csv', index = False)

In [28]:
rating22_new = rating22[new_col_2]
rating21_new = rating21[new_col_2]
rating20_new = rating20[new_col_2]
rating19_new = rating19[new_col_2]
rating18_new = rating18[new_col_2]
rating17_new = rating17[new_col_2]
rating16_new = rating16[new_col_2]

In [32]:
rating22_new.rename(columns = {'nationality_name':'nationality', 'height_cm':'height', 'weight_kg': 'weight'}, inplace = True)
rating21_new.rename(columns = {'nationality_name':'nationality', 'height_cm':'height', 'weight_kg': 'weight'}, inplace = True)
rating20_new.rename(columns = {'nationality_name':'nationality', 'height_cm':'height', 'weight_kg': 'weight'}, inplace = True)
rating19_new.rename(columns = {'nationality_name':'nationality', 'height_cm':'height', 'weight_kg': 'weight'}, inplace = True)
rating18_new.rename(columns = {'nationality_name':'nationality', 'height_cm':'height', 'weight_kg': 'weight'}, inplace = True)
rating17_new.rename(columns = {'nationality_name':'nationality', 'height_cm':'height', 'weight_kg': 'weight'}, inplace = True)
rating16_new.rename(columns = {'nationality_name':'nationality', 'height_cm':'height', 'weight_kg': 'weight'}, inplace = True)

C:\Users\lorih\AppData\Local\Temp\ipykernel_68896\2418996844.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rating22_new.rename(columns = {'nationality_name':'nationality', 'height_cm':'height', 'weight_kg': 'weight'}, inplace = True)
C:\Users\lorih\AppData\Local\Temp\ipykernel_68896\2418996844.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rating21_new.rename(columns = {'nationality_name':'nationality', 'height_cm':'height', 'weight_kg': 'weight'}, inplace = True)
C:\Users\lorih\AppData\Local\Temp\ipykernel_68896\2418996844.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rating20_new.rename(columns = {'nationality_name':'nationality', 'height_cm':'height', 'weight_kg': 'weight'}, inplace = True)
C:\Users\lorih\AppData\Local\Temp\ipykernel_68896\2418996844.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rating19_new.rename(columns = {'nationality_name':'nationality', 'height_cm':'height', 'weight_kg': 'weight'}, inplace = True)
C:\Users\lorih\AppData\Local\Temp\ipykernel_68896\2418996844.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rating18_new.rename(columns = {'nationality_name':'nationality', 'height_cm':'height', 'weight_kg': 'weight'}, inplace = True)
C:\Users\lorih\AppData\Local\Temp\ipykernel_68896\2418996844.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rating17_new.rename(columns = {'nationality_name':'nationality', 'height_cm':'height', 'weight_kg': 'weight'}, inplace = True)
C:\Users\lorih\AppData\Local\Temp\ipykernel_68896\2418996844.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rating16_new.rename(columns = {'nationality_name':'nationality', 'height_cm':'height', 'weight_kg': 'weight'}, inplace = True)

In [34]:
rating22_new.to_csv('../Datasets/cleaned_data/FIFA22_rating_new.csv', index = False)
rating21_new.to_csv('../Datasets/cleaned_data/FIFA21_rating_new.csv', index = False)
rating20_new.to_csv('../Datasets/cleaned_data/FIFA20_rating_new.csv', index = False)
rating19_new.to_csv('../Datasets/cleaned_data/FIFA19_rating_new.csv', index = False)
rating18_new.to_csv('../Datasets/cleaned_data/FIFA18_rating_new.csv', index = False)
rating17_new.to_csv('../Datasets/cleaned_data/FIFA17_rating_new.csv', index = False)
rating16_new.to_csv('../Datasets/cleaned_data/FIFA16_rating_new.csv', index = False)

In [35]:
rating16_22 = pd.concat([rating16_new, rating17_new, rating18_new, rating19_new, rating20_new, rating21_new, rating22_new], ignore_index = True)

In [36]:
rating16_22.to_csv('../Datasets/cleaned_data/FIFA16-22_rating_new.csv', index = False)